"""empty message

Revision ID: 3c8403bd357f
Revises: 002764274088
Create Date: 2020-12-08 23:12:04.019987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c8403bd357f'
down_revision = '002764274088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('name_city', sa.String(length=50), nullable=False))
    op.drop_column('cities', 'name')
    op.add_column('users', sa.Column('user_name', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_name')
    op.add_column('cities', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cities', 'name_city')
    # ### end Alembic commands ###
