"""empty message

Revision ID: 7fa271beba75
Revises: 3c8403bd357f
Create Date: 2020-12-09 16:49:35.008276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fa271beba75'
down_revision = '3c8403bd357f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('city_name', sa.String(length=50), nullable=False))
    op.drop_column('cities', 'name_city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('name_city', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cities', 'city_name')
    # ### end Alembic commands ###
