"""empty message

Revision ID: fd8285b0d84e
Revises: 590af38f6b63
Create Date: 2021-01-20 18:00:41.545949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd8285b0d84e'
down_revision = '590af38f6b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('average_highest_temp', sa.String(length=150), nullable=False))
    op.add_column('cities', sa.Column('average_lowest_temp', sa.String(length=150), nullable=False))
    op.add_column('cities', sa.Column('population_density', sa.String(length=150), nullable=False))
    op.drop_column('cities', 'sunny')
    op.drop_column('cities', 'windy')
    op.drop_column('cities', 'rainy')
    op.drop_column('cities', 'lowest_temp')
    op.drop_column('cities', 'rental_offer')
    op.drop_column('cities', 'average_temp')
    op.drop_column('cities', 'humidity')
    op.drop_column('cities', 'highest_temp')
    op.drop_column('users', 'active')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('cities', sa.Column('highest_temp', mysql.FLOAT(), nullable=False))
    op.add_column('cities', sa.Column('humidity', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cities', sa.Column('average_temp', mysql.FLOAT(), nullable=False))
    op.add_column('cities', sa.Column('rental_offer', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cities', sa.Column('lowest_temp', mysql.FLOAT(), nullable=False))
    op.add_column('cities', sa.Column('rainy', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cities', sa.Column('windy', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cities', sa.Column('sunny', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('cities', 'population_density')
    op.drop_column('cities', 'average_lowest_temp')
    op.drop_column('cities', 'average_highest_temp')
    # ### end Alembic commands ###
