"""empty message

Revision ID: feb22dacd5ed
Revises: 6e9b446eefd6
Create Date: 2021-01-05 20:41:38.913435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'feb22dacd5ed'
down_revision = '6e9b446eefd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
